/** Deterministic chat-facing scheduling tools. They own Redis writes so an LLM
 * cannot bypass confirmation by merely emitting a convincing sentence. */
import { clearPendingScheduledPlan, createScheduledTask, createUserSubscription, deleteScheduledTask, getBindByPeer, getPendingScheduledPlan, getPersonasByIds, getSystemSubscriptionService, isServiceOpenToPersona, listPeerScheduledTasks, listSystemSubscriptionServices, resolvePersonaForPeer, savePendingScheduledPlan, updateScheduledTask, validateSubscriptionParams } from "@wechat-ai/db";
import type { Db } from "@wechat-ai/db";

const YES=/^\s*(确认|可以|创建|确定|好的|好)\s*[！!。.]?\s*$/;
const NO=/^\s*(取消|不用了|算了|不要)\s*[！!。.]?\s*$/;
function scheduleOf(text:string){const hm=text.match(/(?:每天|每日).{0,8}?(?:早上|上午|中午|下午|晚上)?\s*(\d{1,2})(?:点|:|：)(\d{1,2})?/);if(!hm)return null;let h=Number(hm[1]),m=Number(hm[2]||0);if(/下午|晚上/.test(text)&&h<12)h+=12;if(h>23||m>59)return null;return `${m} ${h} * * *`;}
function nameOf(text:string){return text.replace(/每天.*?(?:提醒我|给我|查一下|查|发给我)/," ").replace(/[。！!]/g,"").trim().slice(0,40)||"定时任务";}
export async function handleScheduledChatTool(db:Db,input:{botId:string;peerId:string;text:string}):Promise<string|null>{
  const text=input.text.trim(); const pending=await getPendingScheduledPlan(db,input.botId,input.peerId);
  if(pending?.kind === "subscription" && typeof pending.payload.collecting === "string") {
    const key = pending.payload.collecting; const service=await getSystemSubscriptionService(db,String(pending.payload.service_id));
    if(!service) { await clearPendingScheduledPlan(db,input.botId,input.peerId); return "该订阅服务已不可用。"; }
    const params={...((pending.payload.params as Record<string,unknown>)||{}),[key]:text};
    const errors=validateSubscriptionParams(service.params_schema,params);
    const missing=errors.find(x=>x.startsWith("missing:"));
    if(missing){const next=missing.slice(8);await savePendingScheduledPlan(db,{...pending,payload:{...pending.payload,params,collecting:next}});return `还需要填写 ${next}。`;}
    if(errors.length)return "参数格式不符合该订阅服务要求，请重新填写。";
    await savePendingScheduledPlan(db,{...pending,payload:{...pending.payload,params,collecting:null}});
    return `准备订阅：\n${service.name}\n${service.schedule}（${service.timezone}）\n确认订阅吗？`;
  }
  if(pending&&YES.test(text)) { if(pending.kind==="task"){await clearPendingScheduledPlan(db,input.botId,input.peerId);const p=pending.payload;const task=await createScheduledTask(db,{user_id:pending.user_id,bot_id:pending.bot_id,peer_id:pending.peer_id,persona_id:pending.persona_id,name:String(p.name),prompt:String(p.prompt),schedule:String(p.schedule),timezone:String(p.timezone),web_search_enabled:Number(p.web_search_enabled)||0,enabled:1});return `已创建「${task.name}」。`; } if(pending.kind==="subscription"){const p=pending.payload;const service=await getSystemSubscriptionService(db,String(p.service_id));const params=(p.params as Record<string,unknown>)||{};if(!service?.enabled||!(await isServiceOpenToPersona(db,service.id,pending.persona_id))||validateSubscriptionParams(service.params_schema,params).length)return "该订阅计划已失效，请重新发起订阅。";await clearPendingScheduledPlan(db,input.botId,input.peerId);await createUserSubscription(db,{user_id:pending.user_id,bot_id:pending.bot_id,peer_id:pending.peer_id,persona_id:pending.persona_id,service_id:service.id,params,enabled:1});return `已订阅，之后会按计划推送。`;} if(pending.kind==="task_cancel"){await clearPendingScheduledPlan(db,input.botId,input.peerId);await deleteScheduledTask(db,String(pending.payload.task_id));return "已删除该定时任务。";} if(pending.kind==="task_update"){await clearPendingScheduledPlan(db,input.botId,input.peerId);await updateScheduledTask(db,String(pending.payload.task_id),pending.payload.patch as {enabled?:number;schedule?:string});return "已更新该定时任务。";}}
  if(pending&&NO.test(text)){await clearPendingScheduledPlan(db,input.botId,input.peerId);return "已取消待确认的定时操作。";}
  const bind=await getBindByPeer(db,input.botId,input.peerId);const userId=bind?.userId||`wechat:${input.botId}:${input.peerId}`;
  if(/^(我的)?定时任务[？?！!。.]?$/.test(text)){const tasks=await listPeerScheduledTasks(db,input.botId,input.peerId);if(!tasks.length)return "你现在还没有自建定时任务。";const personas=await getPersonasByIds(db,tasks.map(x=>x.persona_id));return `你现在有 ${tasks.length} 个自建任务：\n`+tasks.map((x,i)=>`${i+1}. ${x.name}\n   ${x.schedule}（${x.timezone}）\n   人设：${personas.get(x.persona_id)?.display_name||"已不可用"}\n   ${x.enabled?"已启用":"已暂停"}`).join("\n");}
  const ownTasks=await listPeerScheduledTasks(db,input.botId,input.peerId); const target=ownTasks.find(t=>text.includes(t.name));
  if(target&&/(取消|删除)/.test(text)){await savePendingScheduledPlan(db,{kind:"task_cancel",user_id:userId,bot_id:input.botId,peer_id:input.peerId,persona_id:target.persona_id,payload:{task_id:target.id},created_at:new Date().toISOString()});return `准备删除「${target.name}」，确认吗？`;}
  if(target&&/(暂停|恢复|启用|改成)/.test(text)){const s=scheduleOf(text);const patch=s?{schedule:s}: {enabled:/暂停/.test(text)?0:1};await savePendingScheduledPlan(db,{kind:"task_update",user_id:userId,bot_id:input.botId,peer_id:input.peerId,persona_id:target.persona_id,payload:{task_id:target.id,patch},created_at:new Date().toISOString()});return `准备更新「${target.name}」，确认吗？`;}
  if(/有什么可以订阅|可订阅/.test(text)){const persona=await resolvePersonaForPeer(db,input.botId,input.peerId);if(!persona)return "当前没有可用人设。";const all=await listSystemSubscriptionServices(db);const available=[] as typeof all;for(const s of all)if(await isServiceOpenToPersona(db,s.id,persona.id))available.push(s);return available.length?`当前可以订阅：\n${available.map((s,i)=>`${i+1}. ${s.name}`).join("\n")}`:"当前人设没有开放订阅服务。";}
  if(/^订阅/.test(text)){const persona=await resolvePersonaForPeer(db,input.botId,input.peerId);const services=await listSystemSubscriptionServices(db);const service=services.find(s=>text.includes(s.name));if(!persona||!service||!(await isServiceOpenToPersona(db,service.id,persona.id)))return "没有找到当前人设可订阅的服务。";const required=Array.isArray(service.params_schema.required)?service.params_schema.required.find((x):x is string=>typeof x==="string"):undefined;await savePendingScheduledPlan(db,{kind:"subscription",user_id:userId,bot_id:input.botId,peer_id:input.peerId,persona_id:persona.id,payload:{service_id:service.id,params:{},collecting:required||null},created_at:new Date().toISOString()});return required?`你想订阅的 ${required} 是什么？`:`准备订阅：\n${service.name}\n${service.schedule}（${service.timezone}）\n确认订阅吗？`;}
  const schedule=scheduleOf(text);if(schedule&&/(提醒|查|新闻|天气|发给我|给我)/.test(text)){const persona=await resolvePersonaForPeer(db,input.botId,input.peerId);if(!persona)return "当前没有可用人设。";const name=nameOf(text);const web=/联网|新闻|天气|查/.test(text);await savePendingScheduledPlan(db,{kind:"task",user_id:userId,bot_id:input.botId,peer_id:input.peerId,persona_id:persona.id,payload:{name,prompt:text,schedule,timezone:"Asia/Shanghai",web_search_enabled:web?1:0},created_at:new Date().toISOString()});return `准备创建定时任务：\n任务：${name}\n执行计划：${schedule}（Asia/Shanghai）\n人设：${persona.display_name}\n操作：${text}\n确认创建吗？`;}
  return null;
}
